#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE ROLE lisp_ro WITH LOGIN PASSWORD 'lisp_ro';
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO lisp_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT SELECT ON TABLES TO lisp_ro;
EOSQL
